### ISSUE TITLE
As an administrator, I want to have tools to monitor and moderate custom blocks in the gallery to maintain a safe and productive community.

### ISSUE THREAD

**Issue by npgilman** [CEN3031-Group7c/sapphire-project06-7c#2]
### Acceptance Criteria
- [ ] Criteria 1
- [ ] Criteria 2

### Tasks
- [ ] Allow administrators to delete custom blocks
- [ ] Allow administrators to disable or change blocks
- [ ] Allow administrators to monitor blocks
