### ISSUE TITLE
As a user, I want to be able to create blocks that successfully detect my sensors.

### ISSUE THREAD

**Issue by npgilman** [CEN3031-Group7c/sapphire-project06-7c#3]
### Acceptance Criteria
- [ ] Criteria 1
- [ ] Criteria 2

### Tasks
- [ ] Research how Arduino code works with Sensors
- [ ] Review current code and what is already implemented
- [ ] Implement the sensors that could be used
