### ISSUE TITLE
As a user, I want to be able to generate new blocks without leaving the website.

### ISSUE THREAD

**Issue by npgilman** [CEN3031-Group7c/sapphire-project06-7c#5]
### Acceptance Criteria
- [ ] Criteria 1
- [ ] Criteria 2

### Tasks
- [ ] Become familiarized with website
- [ ] Consolidate all aspects of block generation to one website/page
- [ ] Design / clean up interface
