### ISSUE TITLE
As a user, I want to have clear and easy-to-follow instructions for creating, sharing, and using custom blocks within the app.

### ISSUE THREAD

**Issue by npgilman** [CEN3031-Group7c/sapphire-project06-7c#6]
### Acceptance Criteria
- [ ] Criteria 1
- [ ] Criteria 2

### Tasks
- [ ] Research codebase and setup project 
- [ ] Allow users to create custom blocks 
- [ ] Become familiarized with website
- [ ] Consolidate all aspects of block generation to one website/page
