### ISSUE TITLE
As a user, I want to share my custom blocks with the community by adding them to the gallery.

### ISSUE THREAD

**Issue by npgilman** [CEN3031-Group7c/sapphire-project06-7c#7]
### Acceptance Criteria
- [ ] Criteria 1
- [ ] Criteria 2

### Tasks
- [ ] Research scope of project and determine conflicts with gallery project 
- [ ] Create mock gallery database for custom blocks/ collaborate with gallery project for storage implementation
- [ ] Create or configure database API to account for different users and introduce security
- [ ] Design and implement share feature front end
- [ ] Design and implement block check for innappropriate content
