### ISSUE TITLE
As a user, I want to see a prettier toolbox with improved design and user experience for accessing custom blocks.

### ISSUE THREAD

**Issue by npgilman** [CEN3031-Group7c/sapphire-project06-7c#8]
### Acceptance Criteria
- [ ] Criteria 1
- [ ] The toolbox offers a simple and intuitive way to access custom blocks.

### Tasks
- [ ] Research toolboxes from various interfaces 
- [ ] Compile findings into a competitive analysis
- [ ] Research custom block integration
- [ ] Get user suggestions and feedback
- [ ] Integrate into application
