### ISSUE TITLE
As a user, I want to create my own custom blocks to streamline my coding tasks and add them to my personal workspace.

### ISSUE THREAD

**Issue by npgilman** [CEN3031-Group7c/sapphire-project06-7c#9]
### Acceptance Criteria
- [ ] Criteria 1
- [ ] Criteria 2

### Tasks
- [ ] Research methods of storing custom blocks 
- [ ] Review codebase 
- [ ] Create a tab for accessing custom blocks
- [ ] Save blocks as custom
- [ ] Access blocks from the custom tab
